export { login, loginWithAccessToken, loginWithSfCli, loginWithPassword, getCredentialsFromEnv } from "./auth";
export type { SalesforceCredentials } from "./auth";

export {
  createCustomObject,
  createCustomField,
  createPermissionSet,
  createCustomTab,
  createLayout,
  updateLayout,
  createListView,
  createCompactLayout,
  createValidationRule,
  createRecordType,
  readMetadata,
  updateMetadata,
  deleteMetadata,
  listMetadata,
  createPlatformEvent,
  createPlatformEventField,
  publishPlatformEvent,
} from "./metadata";
export type {
  CustomObjectConfig,
  PlatformEventConfig,
  PlatformEventFieldConfig,
  CustomFieldConfig,
  PermissionSetConfig,
  CustomTabConfig,
  LayoutConfig,
  LayoutSection,
  ListViewConfig,
  CompactLayoutConfig,
  ValidationRuleConfig,
  RecordTypeConfig,
} from "./metadata";

export {
  toolingQuery,
  describeObject,
  describeGlobal,
  executeAnonymous,
  getApexClasses,
  getApexTriggers,
  getCustomFields,
  getValidationRules,
} from "./tooling";

export {
  createDataLakeObject,
  readDataLakeObject,
  listDataLakeObjects,
  deleteDataLakeObject,
  createDataTransform,
  listDataTransforms,
  getDataTransform,
  queryDataCloud,
  createCalculatedInsight,
  readCalculatedInsight,
  listCalculatedInsights,
  deleteCalculatedInsight,
  listFieldMappings,
  readFieldMapping,
  createSegment,
  readSegment,
  listSegments,
  deleteSegment,
  listSegmentsRest,
  publishSegment,
  buildSegmentFilter,
  createDataKit,
  readDataKit,
  listDataKits,
  deleteDataKit,
  listDataKitObjects,
  listDataStreamTemplates,
  listIdentityResolutions,
  getIdentityResolution,
  createIdentityResolution,
  runIdentityResolution,
  createAgentAction,
  createAgentTopic,
  readAgentAction,
  readAgentTopic,
  listAgentTopics,
  listAgentActions,
  deployApexClass,
  listActivationTargets,
  getActivationTarget,
  createActivationTarget,
  deleteActivationTarget,
  listActivations,
  getActivation,
  createActivation,
  deleteActivation,
  listActivationPlatforms,
  exchangeDCToken,
  ingestData,
  deleteIngestionData,
  mapTypeToDloDatatype,
  buildFieldsFromSchema,
} from "./data-cloud";
export type {
  DloFieldDatatype,
  DloFieldConfig,
  DloConfig,
  DataTransformConfig,
  CalculatedInsightConfig,
  SegmentConfig,
  SegmentFilterCriteria,
  DCToken,
  AgentActionConfig,
  AgentTopicConfig,
  DataKitConfig,
} from "./data-cloud";
